### ISSUE TITLE
Unique uml graph (unique image) for a whole project

### ISSUE THREAD

**Issue by mathieuanthoine** [ianxm/haxeumlgen#11]
I would like to create one unique uml graph for a whole project.

It seems possible, but I don't know where I have to make changes in haxeumlgen code. Can you give me some help to understand it ?

In the same way, is it possible to:
- exclude some specific classes or packages from the uml graph ?
- hide properties and methods from the uml graph to display only the inheritance between classes (when graphs are too big)

At last, is it possible to create parameters of haxeumlgen for these different cases ?

Thanks for your help

**Comment by ianxm** [comment]
it's certainly possible to make one big graph from a project, but I don't think it'd work out well most of the time.  if there are too many classes the diagram can get difficult to look at, and the classes in the same package wouldn't necessarily be grouped together.

anyway, you'd want to go into the `run` method of the appropriate `IOutputHandler` class and move the loop over packages from the top lower to just contain the loop over `boxes`.  

if you want to exclude some packages you can skip them in that loop.

you could remove the properties and methods by modifying `ClassModel.getDotStr()` for graphviz, or the `IOutputHandler` class for xmi.

if you wanted to add input parameters, you'd do that in `InputHandler`.

I can see a benefit to being able to hide class details, but I don't think it would be good to look at a diagram of a whole project unless it's small enough that you don't really need a diagram.

**Comment by mathieuanthoine** [comment]
Thank you Ian for the explanations.
You're right, in real life, having a whole project diagram can be
unreadable but in my case, the aim is to introduce small projects diagrams
to my students and even if the diagram contains only few classes it would
be really helpful for them to start.

## 

Mathieu

Le 15 juil. 2015 à 03:20, Ian notifications@github.com a écrit :

it's certainly possible to make one big graph from a project, but I don't
think it'd work out well most of the time. if there are too many classes
the diagram can get difficult to look at, and the classes in the same
package wouldn't necessarily be grouped together.

anyway, you'd want to go into the run method of the appropriate
IOutputHandler class and move the loop over packages from the top lower to
just contain the loop over boxes.

if you want to exclude some packages you can skip them in that loop.

you could remove the properties and methods by modifying
ClassModel.getDotStr() for graphviz, or the IOutputHandler class for xmi.

if you wanted to add input parameters, you'd do that in InputHandler.

I can see a benefit to being able to hide class details, but I don't think
it would be good to look at a diagram of a whole project unless it's small
enough that you don't really need a diagram.

**Comment by mathieuanthoine** [comment]
Hi Ian,

Thank you for help.
I have added parameters for package exclusion and hide of properties and
methods.

The last thing I have difficulties with is the whole project diagram but
I'm working on.

At the end I will do a pull request if you're interested.

## 

Mathieu

Le 15 juil. 2015 à 03:20, Ian notifications@github.com a écrit :

it's certainly possible to make one big graph from a project, but I don't
think it'd work out well most of the time. if there are too many classes
the diagram can get difficult to look at, and the classes in the same
package wouldn't necessarily be grouped together.

anyway, you'd want to go into the run method of the appropriate
IOutputHandler class and move the loop over packages from the top lower to
just contain the loop over boxes.

if you want to exclude some packages you can skip them in that loop.

you could remove the properties and methods by modifying
ClassModel.getDotStr() for graphviz, or the IOutputHandler class for xmi.

if you wanted to add input parameters, you'd do that in InputHandler.

I can see a benefit to being able to hide class details, but I don't think
it would be good to look at a diagram of a whole project unless it's small
enough that you don't really need a diagram.
